Snake-Build
===========

Snake build has the goal to provide a simple build server which should be
configurable and usable from the shell and from a web interface. The difference
to existing solutions should be that all configuration and build informations
should be stored with a VCS. With this it must be possible to rebuild old
builds with the same configuration as it was build originally.

== Usage

To get the information how to use the snake build components see the doc
folder. The easiest way to read it build it with make doc and then read the
snake-build.html file.
Read bellow to see the current state to see what currently is working.

== Status

=== Current State

v0.1;;
  This version provides a first implementation of the resource server and the
  resource client. This two components can be used to access resources from an
  existing build server. For example if you have external testing resources
  which can't be managed by the build server you are using then this might
  already be usable.
  There is currently no support for building software and the configuration
  files are not yet stored within a a VCS.

=== Future Roadmap

v0.2;;
  This version should provide the possibility to build software with simple
  build scripts.

v0.3;;
  This version should provide support for getting all the build scripts and the
  config files from a VCS.

v0.x;;
  Get the control an reporting server. This includes a web frontend. A more
  detailed plan will be made after further progress.

v1.0;;
  Everything is working....
