#!/bin/sh 
### BEGIN INIT INFO
# Provides: sb-resourceserver
# Required-Start:   $remote_fs $syslog
# Required-Stop:    $remote_fs $syslog
# Default-Start:    2 3 4 5
# Default-Stop:     
# Short-Description: Start the resource handler server
### END INIT INFO

set -e

export PATH="${PATH}:+${PATH}:/usr/sbin/:sbin"

case "$1" in
  start)
    log_action_msg "Starting the snake build resource server" 
    sb-resourceserver
    ;;
  stop)
    log_action_msg "Stoping the snake build resource server" 
    sb-resourceserver --stop
    ;;
  *)
    log_action_msg "Usage: /etc/init.d/sb-resourceserver {start|stop}"
    exit 1
esac

exit 0

